
name: Firebase Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Admin SDK
        env:
          FIREBASE_ADMIN_SDK_JSON: ${{ secrets.FIREBASE_ADMIN_SDK_JSON }}
        run: |
          echo "${{ secrets.FIREBASE_ADMIN_SDK_JSON }}" > ${HOME}/admin_sdk.json
          export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/admin_sdk.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project 52672873969  # Use the correct project ID here
